CREATE TABLE  "RESERVE" 
   (	"ID" NUMBER, 
	"PASSENGERID" NUMBER NOT NULL, 
	"BUSID" NUMBER NOT NULL, 
	"DT" DATE NOT NULL, 
	"TSTAMP" DATE NOT NULL, 
	"SEAT" NUMBER NOT NULL, 
	 PRIMARY KEY ("ID") ENABLE, 
	 FOREIGN KEY ("PASSENGERID")
	  REFERENCES  "PASSENGER" ("ID") ENABLE, 
	 FOREIGN KEY ("BUSID")
	  REFERENCES  "BUS" ("ID") ENABLE
   )
/