CREATE TABLE  "RESERVE" 
   (	"ID" NUMBER, 
	"PASSENGER_ID" NUMBER NOT NULL, 
	"BUS_ID" NUMBER NOT NULL, 
	"DT" DATE NOT NULL, 
	"TSTAMP" DATE NOT NULL, 
	"SEAT" NUMBER NOT NULL, 
	 PRIMARY KEY ("ID") ENABLE, 
	 FOREIGN KEY ("PASSENGER_ID")
	  REFERENCES  "PASSENGER" ("ID") ENABLE, 
	 FOREIGN KEY ("BUS_ID")
	  REFERENCES  "BUS" ("ID") ENABLE
   )
/